In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
train = pd.read_csv("./train.csv")
test = pd.read_csv("./test.csv")
train

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

# Tutorial - 57%

In [23]:
train_vectors = count_vectorizer.fit_transform(train["text"])
test_vectors = count_vectorizer.transform(test["text"])

In [24]:
clf = linear_model.RidgeClassifier()

In [25]:
scores = model_selection.cross_val_score(clf, train_vectors, train_df["target"], cv=3, scoring="f1")
scores

array([0.59453669, 0.5642787 , 0.64082434])

In [26]:
clf.fit(train_vectors, train_df["target"])

RidgeClassifier()

In [35]:
sample_submission = pd.read_csv("./sample_submission.csv")
sample_submission["target"] = clf.predict(test_vectors)
sample_submission.to_csv("submission.csv", index=False)

ValueError: X has 12279 features, but RidgeClassifier is expecting 21637 features as input.

# Term-Frequency Time Inverse Document Frequency (TF-IDF) - 80%

In [44]:
vectorizer = TfidfVectorizer()

train_vectors = vectorizer.fit_transform(train["text"])
test_vectors = vectorizer.transform(test["text"])
A
clf = linear_model.RidgeClassifier()

scores = model_selection.cross_val_score(clf, train_vectors, train_df["target"], cv=5, scoring="f1")

clf.fit(train_vectors, train_df["target"])


RidgeClassifier()

In [45]:
scores

array([0.62962963, 0.55507372, 0.64457332, 0.59444444, 0.72337043])

In [43]:
sample_submission = pd.read_csv("./sample_submission.csv")
sample_submission["target"] = clf.predict(test_vectors)
sample_submission.to_csv("submission.csv", index=False)

# Latent Semantic Indexing -74%

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import cross_val_score

In [69]:
# Créez un objet vectorizer TF-IDF
vectorizer = TfidfVectorizer()

# Ajustez et transformez les données textuelles
train_vectors = vectorizer.fit_transform(train["text"])
test_vectors = vectorizer.transform(test["text"])

In [88]:
# Créez un objet TruncatedSVD (LSI)
num_components = 50  # Choisissez le nombre de composantes LSI
lsi = TruncatedSVD(n_components=num_components, random_state=100)

# Appliquez LSI aux vecteurs TF-IDF
train_lsi = lsi.fit_transform(train_vectors)
test_lsi = lsi.transform(test_vectors)

In [89]:
# Créez un classifieur Ridge
clf = RidgeClassifier()

# Effectuez une validation croisée sur les vecteurs LSI
scores = cross_val_score(clf, train_lsi, train_df["target"], cv=3, scoring="f1")

# Entraînez le modèle final
clf.fit(train_lsi, train_df["target"])

RidgeClassifier()

In [90]:
scores

array([0.60859978, 0.56128674, 0.61796043])

In [76]:
# Faites des prédictions sur les données de test
sample_submission = pd.read_csv("./sample_submission.csv")
sample_submission["target"] = clf.predict(test_lsi)
sample_submission.to_csv("submission.csv", index=False)

# Neurones Long-Short Term Memory (LSTM) - impossible sans Nvidia Cuda ?

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

2023-10-16 00:49:40.046554: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-16 00:49:40.128037: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-16 00:49:40.130233: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 00:49:41.910879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [ ]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_seq_length))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [111]:
!pip install --upgrade numpy==1.24.3

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 2.4 MB/s eta 0:00:0000:0100:01
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: gpg 1.13.1-unknown has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of gpg or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.36ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement